MINIMA_USER_PREFIX="${MINIMA_USER_PREFIX=""}"
MINIMA_USER_SUFFIX="${MINIMA_USER_SUFFIX=" "}"
MINIMA_USER_COLOR="${MINIMA_USER_COLOR="yellow"}"

minima_module_user() {
  minima::module \
    "$MINIMA_USER_COLOR" \
    "$MINIMA_USER_PREFIX" \
    '%n' \
    "$MINIMA_USER_SUFFIX"
}
